name: Build FastFall Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-game:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build game for web
      run: npm run build:itch
      
    - name: Upload playable game artifact
      uses: actions/upload-artifact@v4
      with:
        name: fastfall-playable-game
        path: dist/itch/
        retention-days: 30
        
    - name: Upload game ZIP file
      uses: actions/upload-artifact@v4
      with:
        name: fastfall-game-zip
        path: dist/fastfall-itch.zip
        retention-days: 30